# cloudbuild.backend.yaml

steps:
  # 1. Build Docker image untuk backend (context: root repo)
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/scribly-backend-v3",
        "."
      ]

  # 2. Push image ke Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/scribly-backend-v3"
      ]

  # 3. Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args:
      [
        "run", "deploy", "scribly-backend-v3",
        "--image", "gcr.io/$PROJECT_ID/scribly-backend-v3",
        "--timeout=1000s",
        "--port=5000",
        "--region=us-central1",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
